### ISSUE TITLE
Replace Resources to something light

### ISSUE THREAD

**Issue by Disinterpreter** [Yuukari/TRex#1]
34 .png files it is good, but didn't you think how Mario's developers keep all textures on 40kb of the memory?

I suggest, to read how our old developers made games and do the same.

I mean replace all PNG to one palette and take the data by offsets from here.

More information: https://youtu.be/jqyC_S56B3k

**Comment by yuukari** [comment]
I know this is not the best way to store sprite data, especially when they use a two-color palette.

I had an idea to store sprite data as arrays or bitmaps. I plan to optimize resources in future versions of the game
